apiVersion :  networking.k8s.io/v1
kind : Ingress
metadata : 
  name : ingress-service
  annotations:
    kkubernetes.io/ingress.class : nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
spec:
  rules:
    - host: ticketing.dev
      http: 
        paths:
          
          - pathType: Prefix
            path : /api/users/?(.*)
            backend :
              # serviceName : auth-srv
              # servicePort : 3000
              service:
                name : auth-srv
                port :
                  number : 3000

          - pathType: Prefix
            path : /?(.*)
            backend :
              # serviceName : client-srv
              # servicePort : 3000
              service:
                name : client-srv
                port :
                  number : 3000